[build]
default-target = "x86_64-unknown-linux-gnu"
dockerfile = "./docker/Dockerfile"
#pre-build = [
#  "dpkg --add-architecture $CROSS_DEB_ARCH",
#  "apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH",
#]

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"
pre-build = ["""
    dpkg --add-architecture amd64 && \
    apt-get update && \
    apt-get install --assume-yes lld clang
    """]

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"
pre-build = ["""
    dpkg --add-architecture amd64 && \
    apt-get update && \
    apt-get install --assume-yes lld clang
    """]

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"
pre-build = ["""
    dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes lld clang
    """]

#[target.armv7-unknown-linux-musleabihf]
#image = "ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:main"
#pre-build = [
#    """
#    apt-get update && \
#    apt-get install --assume-yes lld clang
#    """
#]

#[target.arm-unknown-linux-musleabihf]
#image = "ghcr.io/cross-rs/arm-unknown-linux-musleabihf:main"
#pre-build = [
#    """
#    apt-get update && \
#    apt-get install --assume-yes lld clang
#    """
#]
